version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    # dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/auth-service/main.go

volumes:
  pgdata:
