version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-auth_service}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-auth_service}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-auth_service}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET:-your-very-secure-jwt-secret-key}
    # Remove these lines as they're not needed with the Dockerfile build
    # volumes:
    #   - .:/app
    # working_dir: /app
    # command: go run cmd/auth-service/main.go

volumes:
  postgres_data: